/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppRouteImport } from './pages/_app'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AppTrackOrderIndexRouteImport } from './pages/_app/track-order/index'
import { Route as AppOrderSuccessIndexRouteImport } from './pages/_app/order-success/index'
import { Route as AppCheckoutIndexRouteImport } from './pages/_app/checkout/index'
import { Route as AppShopProductIdRouteImport } from './pages/_app/shop/$productId'
import { Route as AppAuthRegistrationRouteImport } from './pages/_app/auth/registration'
import { Route as AppAuthLoginRouteImport } from './pages/_app/auth/login'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackOrderIndexRoute = AppTrackOrderIndexRouteImport.update({
  id: '/track-order/',
  path: '/track-order/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderSuccessIndexRoute = AppOrderSuccessIndexRouteImport.update({
  id: '/order-success/',
  path: '/order-success/',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutIndexRoute = AppCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => AppRoute,
} as any)
const AppShopProductIdRoute = AppShopProductIdRouteImport.update({
  id: '/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRegistrationRoute = AppAuthRegistrationRouteImport.update({
  id: '/auth/registration',
  path: '/auth/registration',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthLoginRoute = AppAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth/login': typeof AppAuthLoginRoute
  '/auth/registration': typeof AppAuthRegistrationRoute
  '/shop/$productId': typeof AppShopProductIdRoute
  '/checkout': typeof AppCheckoutIndexRoute
  '/order-success': typeof AppOrderSuccessIndexRoute
  '/track-order': typeof AppTrackOrderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/auth/login': typeof AppAuthLoginRoute
  '/auth/registration': typeof AppAuthRegistrationRoute
  '/shop/$productId': typeof AppShopProductIdRoute
  '/checkout': typeof AppCheckoutIndexRoute
  '/order-success': typeof AppOrderSuccessIndexRoute
  '/track-order': typeof AppTrackOrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/auth/login': typeof AppAuthLoginRoute
  '/_app/auth/registration': typeof AppAuthRegistrationRoute
  '/_app/shop/$productId': typeof AppShopProductIdRoute
  '/_app/checkout/': typeof AppCheckoutIndexRoute
  '/_app/order-success/': typeof AppOrderSuccessIndexRoute
  '/_app/track-order/': typeof AppTrackOrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/registration'
    | '/shop/$productId'
    | '/checkout'
    | '/order-success'
    | '/track-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/registration'
    | '/shop/$productId'
    | '/checkout'
    | '/order-success'
    | '/track-order'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/auth/login'
    | '/_app/auth/registration'
    | '/_app/shop/$productId'
    | '/_app/checkout/'
    | '/_app/order-success/'
    | '/_app/track-order/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/track-order/': {
      id: '/_app/track-order/'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof AppTrackOrderIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/order-success/': {
      id: '/_app/order-success/'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof AppOrderSuccessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout/': {
      id: '/_app/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop/$productId': {
      id: '/_app/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof AppShopProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/registration': {
      id: '/_app/auth/registration'
      path: '/auth/registration'
      fullPath: '/auth/registration'
      preLoaderRoute: typeof AppAuthRegistrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login': {
      id: '/_app/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AppAuthLoginRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAuthLoginRoute: typeof AppAuthLoginRoute
  AppAuthRegistrationRoute: typeof AppAuthRegistrationRoute
  AppShopProductIdRoute: typeof AppShopProductIdRoute
  AppCheckoutIndexRoute: typeof AppCheckoutIndexRoute
  AppOrderSuccessIndexRoute: typeof AppOrderSuccessIndexRoute
  AppTrackOrderIndexRoute: typeof AppTrackOrderIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAuthLoginRoute: AppAuthLoginRoute,
  AppAuthRegistrationRoute: AppAuthRegistrationRoute,
  AppShopProductIdRoute: AppShopProductIdRoute,
  AppCheckoutIndexRoute: AppCheckoutIndexRoute,
  AppOrderSuccessIndexRoute: AppOrderSuccessIndexRoute,
  AppTrackOrderIndexRoute: AppTrackOrderIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
